import { useMemo, useState } from "react";
import type { EChartsOption } from "echarts";
import { DownloadSimple, Info, ShieldCheck } from "@phosphor-icons/react";
import { EChart } from "../../components/EChart";
import { Panel } from "../../components/Panel";
import { StateView } from "../../components/StateView";
import { useApi } from "../../hooks/useApi";
import { useVNextChartPalette } from "../theme";

type FundType = "otc" | "exchange" | "reits";
interface FundPayload { symbol:string; fundType:FundType; source:string; panels:Record<string,unknown>; issues:Array<{panel:string;endpoint:string;message:string}>; pit:Record<string,string>; provenance:Record<string,string|null>; }
function itemRows(value: unknown): Array<Record<string, unknown>> { if (!value || typeof value !== "object") return []; const item=(value as {item?:unknown}).item; return Array.isArray(item)?item.filter((row):row is Record<string,unknown>=>Boolean(row&&typeof row==="object")):[]; }
function asNumber(value: unknown): number|null { const n=typeof value==="number"?value:Number(value); return Number.isFinite(n)?n:null; }
function formatDateMs(value: unknown): string { const n=asNumber(value); if(n===null)return "—"; const d=new Date(n); return Number.isNaN(d.getTime())?"—":d.toISOString().slice(0,10); }
function downloadOffline(payload: FundPayload): void { const encoded=JSON.stringify(payload).replace(/</g,"\\u003c"); const html=`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${payload.symbol} 基金研究</title><style>body{font:14px system-ui;margin:0;background:#0d1117;color:#e6edf3}main{max-width:1100px;margin:auto;padding:28px}.card{background:#161b22;border:1px solid #30363d;border-radius:12px;padding:16px;margin:12px 0}pre{white-space:pre-wrap;word-break:break-word;color:#c9d1d9}</style></head><body><main><small>QuantAgent · Fuyao Fund Research · 非投资建议</small><h1>${payload.symbol}</h1><div class="card"><p>基金类型：${payload.fundType}</p><p>持仓和持有人结构为定期披露，不代表实时持仓。缺失数据不会用模拟数据补齐。</p></div><div class="card"><pre id="data"></pre></div></main><script>const data=${encoded};document.getElementById('data').textContent=JSON.stringify(data,null,2);</script></body></html>`; const blob=new Blob([html],{type:"text/html;charset=utf-8"}); const url=URL.createObjectURL(blob); const a=document.createElement("a"); a.href=url;a.download=`quantagent-fund-${payload.symbol}.html`;a.click();URL.revokeObjectURL(url); }

export function FundResearchPage(): JSX.Element {
  const palette=useVNextChartPalette(); const [fundType,setFundType]=useState<FundType>("exchange"); const [symbol,setSymbol]=useState("510300.SH");
  const query=useApi<FundPayload>(["fund-research",fundType,symbol],"/market/funds/overview",{fundType,symbol},{staleTime:5*60_000}); const payload=query.data?.data;
  const navRows=itemRows(payload?.panels.nav), holdingRows=itemRows(payload?.panels.holdings), returnRows=itemRows(payload?.panels.returns), holderRows=itemRows(payload?.panels.holders), profileRows=itemRows(payload?.panels.profile);
  const option=useMemo<EChartsOption>(()=>{ const sorted=[...navRows].sort((a,b)=>Number(a.date_ms??a.nav_date_ms??0)-Number(b.date_ms??b.nav_date_ms??0)); const labels=sorted.map(r=>formatDateMs(r.date_ms??r.nav_date_ms??r.trade_date_ms)); return {animation:false,tooltip:{trigger:"axis"},legend:{data:["单位净值","复权/累计净值"]},grid:{left:58,right:24,top:38,bottom:54},xAxis:{type:"category",data:labels,axisLabel:{hideOverlap:true}},yAxis:{type:"value",scale:true},dataZoom:[{type:"inside"},{type:"slider",height:18,bottom:8}],series:[{name:"单位净值",type:"line",showSymbol:false,data:sorted.map(r=>asNumber(r.unit_nav??r.nav??r.unit_value)),lineStyle:{color:palette.primary,width:2}},{name:"复权/累计净值",type:"line",showSymbol:false,data:sorted.map(r=>asNumber(r.adj_nav??r.adjusted_nav??r.accum_nav)),lineStyle:{color:palette.series[1]}}]}; },[navRows,palette]);
  return <div className="page fund-research-page"><section className="panel fund-hero"><div><span className="fund-kicker"><ShieldCheck size={16}/> Fuyao Fund Research</span><h2>基金 / ETF / REITs 研究台</h2><p>净值、区间收益、披露持仓、持有人结构和 ETF 场内行情统一查看；所有真实数据由后端读取环境变量凭据。</p></div>{payload?<button className="primary-button" onClick={()=>downloadOffline(payload)}><DownloadSimple size={16}/> 导出离线 HTML</button>:null}</section>
  <section className="panel fund-controls"><label>基金类型<select value={fundType} onChange={e=>setFundType(e.target.value as FundType)}><option value="exchange">ETF / LOF</option><option value="otc">场外基金</option><option value="reits">公募 REITs</option></select></label><label>thscode<input value={symbol} onChange={e=>setSymbol(e.target.value.toUpperCase())}/></label><div className="fund-contract"><Info size={16}/><span>持仓为定期披露；exchange 场内行情由上游 ETF-only 能力决定，LOF 无行情时如实显示 unavailable。</span></div></section>
  {query.isLoading?<StateView state="loading"/>:null}{!query.isLoading&&!payload?<StateView state="empty" title="没有基金研究产物" detail="Fuyao 基金接口没有为该基金类型/代码返回数据；不会用模拟净值补齐。下一步：换一个基金代码或类型，或在治理页确认该数据源可达。" />:null}{payload?<><section className="fund-metric-grid">{returnRows.slice(0,8).map((row,i)=><Panel key={i} title={String(row.period??row.range??row.name??`区间 ${i+1}`)}><strong>{asNumber(row.return_rate??row.return_pct??row.value)===null?"—":`${asNumber(row.return_rate??row.return_pct??row.value)?.toFixed(2)}%`}</strong></Panel>)}</section><section className="panel fund-chart"><EChart option={option} style={{ height: 390 }}/></section><section className="fund-grid"><Panel title="基金资料" eyebrow={payload.symbol}><pre>{JSON.stringify(profileRows[0]??payload.panels.profile??{},null,2)}</pre></Panel><Panel title="持有人结构" eyebrow="Periodic disclosure"><div className="fund-table"><table><thead><tr><th>报告日</th><th>口径</th><th>机构%</th><th>个人%</th><th>户数</th></tr></thead><tbody>{holderRows.map((row,i)=><tr key={i}><td>{formatDateMs(row.report_date_ms)}</td><td>{String(row.merge_scope??"—")}</td><td>{String(row.ins_position??"—")}</td><td>{String(row.psnl_rate??"—")}</td><td>{String(row.holder_amount??"—")}</td></tr>)}</tbody></table></div></Panel></section><section className="panel"><h3>定期披露重仓</h3><div className="fund-table"><table><thead><tr><th>代码</th><th>名称</th><th>净值占比</th><th>报告日</th></tr></thead><tbody>{holdingRows.slice(0,30).map((row,i)=><tr key={i}><td>{String(row.thscode??row.ticker??"—")}</td><td>{String(row.name??"—")}</td><td>{String(row.nav_ratio??row.position_ratio??row.weight??"—")}</td><td>{formatDateMs(row.report_date_ms)}</td></tr>)}</tbody></table></div></section>{payload.issues.length?<Panel title="上游缺口" eyebrow={`${payload.issues.length} issues`}><ul>{payload.issues.map((issue,i)=><li key={i}><code>{issue.panel}</code> · {issue.message}</li>)}</ul></Panel>:null}<Panel title="PIT / 数据口径" eyebrow="No synthetic fallback"><pre>{JSON.stringify({pit:payload.pit,provenance:payload.provenance},null,2)}</pre></Panel></>:null}</div>;
}
